name: "default"
logging: !include logging.yml
server: !include server.yml
facebook_export_dir: /Users/gruberdiego/Downloads/fb_export/
instagram_export_dir: /Users/gruberdiego/Downloads/diegogruber_20220111/
blog_dir: /Users/gruberdiego/Documents/socialmedia/
author: Diego